[project]
name = "project-hub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pytest", "streamlit", "python-dotenv"]

[tool.pytest.ini_options]
pythonpath = "."